num1=5
num2=6
print(num1>num2)
print(num1<num2)
print(5>6)
print(5<6)
print(5==6)
print(5==5)
print(5!=5)
print(5!=6)
print('\n')
print(5>=6)
print(5<=6)
print(6>=5)
print(5>=5)
print(int('5') <= int('6'))
print('\n')
print(False and False)
print(False and True)
print(True and False)
print(True and True)
print('\n')
print(False or False)
print(False or True)
print(True or False)
print(True or True)
print('\n')
print(not False)
print(not True)
print('\n')
print(5>6 or 8>2)
print(5>6 or 8<13)
print(5==5 and 2==(10/5))
print(2!=4 and 4<2)
